# Generated by Django 3.1.3 on 2021-01-31 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0002_shipmentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentorder',
            name='ShipmentAgency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.shipmentagency'),
        ),
        migrations.AddField(
            model_name='shipmentorder',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
