# Generated by Django 3.1.3 on 2021-02-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creditScore',
            field=models.IntegerField(default=100000),
        ),
    ]
